### ISSUE TITLE
Redirect urls are wrong

### ISSUE THREAD

**Issue by Rudra-Garg** [Rudra-Garg/PILGRIMAI#9]
[Screencast from 2024-01-14 22-06-28.webm](https://github.com/Rudra-Garg/PILGRIMAI/assets/121709697/16e75aca-3780-40aa-9562-a369739cd348)
The urls are wrong for every page

**Comment by ShauryaManiTripathi** [comment]
minor prob taken care of along with local sessionID+cookie(new) system
